In [23]:
import pandas as pd
import numpy as np

In [24]:
path = "E:\\Data Science Salarys\\Data\\raw\\ds_salaries.csv"
df = pd.read_csv(path, sep=",")

In [25]:
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [26]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [27]:
# Renomear colunas para português

df['experience_level'] = df['experience_level'].replace({
    'EN': 'Junior',
    'MI': 'Pleno',
    'SE': 'Senior',
    'EX': 'Executive'
})

df['employment_type'] = df['employment_type'].replace({
    'PT': 'Meio período',
    'FT': 'Tempo integral',
    'CT': 'Contrato',
    'FL': 'Freelancer'
})


df['company_size'] = df['company_size'].replace({
    'S': 'Pequena',
    'M': 'Média',
    'L': 'Grande'
})

df['remote_ratio'] = df['remote_ratio'].replace({
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
})

df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,Pleno,Tempo integral,Data Scientist,70000,EUR,79833,DE,Presencial,DE,Grande
1,2020,Senior,Tempo integral,Machine Learning Scientist,260000,USD,260000,JP,Presencial,JP,Pequena
2,2020,Senior,Tempo integral,Big Data Engineer,85000,GBP,109024,GB,Híbrido,GB,Média
3,2020,Pleno,Tempo integral,Product Data Analyst,20000,USD,20000,HN,Presencial,HN,Pequena
4,2020,Senior,Tempo integral,Machine Learning Engineer,150000,USD,150000,US,Híbrido,US,Grande

In [28]:
# Converter colunas para tipos adequados

df['salary'] = df['salary'].astype('float')
df['salary_in_usd'] = df['salary_in_usd'].astype('float')
df['remote_ratio'] = df['remote_ratio'].astype('category')
df['experience_level'] = df['experience_level'].astype('category')
df['employment_type'] = df['employment_type'].astype('category')
df['company_size'] = df['company_size'].astype('category')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           607 non-null    int64
 1   experience_level    607 non-null    category
 2   employment_type     607 non-null    category
 3   job_title           607 non-null    str
 4   salary              607 non-null    float64
 5   salary_currency     607 non-null    str
 6   salary_in_usd       607 non-null    float64
 7   employee_residence  607 non-null    str
 8   remote_ratio        607 non-null    category
 9   company_location    607 non-null    str
 10  company_size        607 non-null    category
dtypes: category(4), float64(2), int64(1), str(4)
memory usage: 36.1 KB

In [29]:
# Criar nova coluna "Área de Atuação" com base no cargo

regras = {
    'Cientista de Dados': [
        'scientist', 'science', 'machine learning', 'researcher', '3d'
    ],
    'Analista de Dados': [
        'analyst', 'analytics'
    ],
    'Engenheiro de Dados': [
        'engineer', 'etl'
    ],
    'Arquiteto de Dados': [
        'architect'
    ],
    'Gerente de Dados': [
        'manager', 'head', 'specialist'
    ]
}

def categorizar(cargo):
    cargo = str(cargo).lower()
    
    for categoria, palavras in regras.items():
        if any(palavra in cargo for palavra in palavras):
            return categoria
    
    return 'Outros'

df['Área_de_Atuação'] = df['job_title'].apply(categorizar)

In [30]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,Área_de_Atuação
0,2020,Pleno,Tempo integral,Data Scientist,70000.0,EUR,79833.0,DE,Presencial,DE,Grande,Cientista de Dados
1,2020,Senior,Tempo integral,Machine Learning Scientist,260000.0,USD,260000.0,JP,Presencial,JP,Pequena,Cientista de Dados
2,2020,Senior,Tempo integral,Big Data Engineer,85000.0,GBP,109024.0,GB,Híbrido,GB,Média,Engenheiro de Dados
3,2020,Pleno,Tempo integral,Product Data Analyst,20000.0,USD,20000.0,HN,Presencial,HN,Pequena,Analista de Dados
4,2020,Senior,Tempo integral,Machine Learning Engineer,150000.0,USD,150000.0,US,Híbrido,US,Grande,Cientista de Dados

In [31]:
# Renomear colunas para português

df = df.rename(columns={'work_year': 'Ano_de_Trabalho', 
                        'experience_level': 'Nivel_de_Experiencia', 
                        'employment_type': 'Tipo_de_Emprego', 
                        'job_title': 'Cargo', 
                        'salary': 'Salario', 
                        'salary_currency': 'Moeda_do_Salario', 
                        'salary_in_usd': 'Salario_em_USD', 
                        'employee_residence': 'Residencia_do_Funcionario', 
                        'remote_ratio': 'Tipo_de_Contrato', 
                        'company_location': 'Localizacao_da_Empresa', 
                        'company_size': 'Tamanho_da_Empresa'})

In [ ]:
# Salvar o DataFrame limpo em um novo arquivo CSV

df.to_csv("E:\\Data Science Salarys\\Data\\cleaned\\ds_salaries_limpo.csv", sep=',', decimal=',')

: